<button class="button button2">Select</button>
<button class="button button2">Shadow on Hover</button>
<button class="button button2">Shadow on Hover</button>
<button class="button button2">Shadow on Hover</button>
<button class="button button2">Shadow on Hover</button>
<button class="button button2">Shadow on Hover</button>
<button class="button button2">Shadow on Hover</button>
<button class="button button2">Shadow on Hover</button>
<button class="button button2">Shadow on Hover</button>
<button class="button button2">Shadow on Hover</button>
<button class="button button2">Shadow on Hover</button>
<button class="button button2">Shadow on Hover</button>
<button class="button button2">Shadow on Hover</button>
<button class="button button2">Shadow on Hover</button>